version: "3.9"
networks:
  default:
    name: "petstore-net"
services:
  petstore:
    image: demo/petstore
    build:
      context: .
      dockerfile: docker/petstore/Dockerfile
    ports:
     - "8081:8080"
     - "5050:5050"
  nginx:
    image: demo/nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:8080"
